### ISSUE TITLE
谁想接手，告诉我一声，快点，必须有人接手，1天之内告诉我

### ISSUE THREAD

**Issue by Xiangrui2019** [Xiangrui2019/dogego#5]
再见，opensource，不干了，谁想接手，我简直要被气死，谁想接手快点，直接issue下面commit，一天之内，不然我就随机选俩star过的当接手的

帮我把cli写好，加上代码生成器。

**Comment by doreamon95** [comment]
我负责写readme.md等这些说明性东西，你搞技术吧

**Comment by Xiangrui2019** [comment]
> 我负责写readme.md等这些说明性东西，你搞技术吧
好吧，有bug别找我，找@bydmm

**Comment by doreamon95** [comment]
> > 我负责写readme.md等这些说明性东西，你搞技术吧
> > 好吧，有bug别找我，找@bydmm

我前期这个能力欠缺了些，后期就可参与技术维护

**Comment by Xiangrui2019** [comment]
> > > 我负责写readme.md等这些说明性东西，你搞技术吧
> > > 好吧，有bug别找我，找@bydmm
> 
> 我前期这个能力欠缺了些，后期就可参与技术维护

@bydmm

**Comment by L-HeliantHuS** [comment]
感觉不够轻量了，接不动.

**Comment by fumeboy** [comment]
然而star过的人不都在自己写框架嘛

**Comment by Xiangrui2019** [comment]
> 感觉不够轻量了，接不动.
去接jrpc，那个轻量的要死

**Comment by Xiangrui2019** [comment]
@L-HeliantHuS
